// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: fileproto/filetransfer.proto

package fileproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datafile string `protobuf:"bytes,1,opt,name=datafile,proto3" json:"datafile,omitempty"`
	Start    int32  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Length   int32  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	CValue   int32  `protobuf:"varint,4,opt,name=cValue,proto3" json:"cValue,omitempty"`
}

func (x *FileSegmentRequest) Reset() {
	*x = FileSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileproto_filetransfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSegmentRequest) ProtoMessage() {}

func (x *FileSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fileproto_filetransfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSegmentRequest.ProtoReflect.Descriptor instead.
func (*FileSegmentRequest) Descriptor() ([]byte, []int) {
	return file_fileproto_filetransfer_proto_rawDescGZIP(), []int{0}
}

func (x *FileSegmentRequest) GetDatafile() string {
	if x != nil {
		return x.Datafile
	}
	return ""
}

func (x *FileSegmentRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FileSegmentRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FileSegmentRequest) GetCValue() int32 {
	if x != nil {
		return x.CValue
	}
	return 0
}

type FileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataChunk []byte `protobuf:"bytes,1,opt,name=dataChunk,proto3" json:"dataChunk,omitempty"`
}

func (x *FileData) Reset() {
	*x = FileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fileproto_filetransfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_fileproto_filetransfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_fileproto_filetransfer_proto_rawDescGZIP(), []int{1}
}

func (x *FileData) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

var File_fileproto_filetransfer_proto protoreflect.FileDescriptor

var file_fileproto_filetransfer_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x76, 0x0a, 0x12, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x57, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1f, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x6b, 0x74, 0x61, 0x72, 0x2d, 0x67, 0x69, 0x66, 0x2f,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x32, 0x2d, 0x36, 0x31, 0x31, 0x2f, 0x66, 0x69,
	0x6c, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fileproto_filetransfer_proto_rawDescOnce sync.Once
	file_fileproto_filetransfer_proto_rawDescData = file_fileproto_filetransfer_proto_rawDesc
)

func file_fileproto_filetransfer_proto_rawDescGZIP() []byte {
	file_fileproto_filetransfer_proto_rawDescOnce.Do(func() {
		file_fileproto_filetransfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_fileproto_filetransfer_proto_rawDescData)
	})
	return file_fileproto_filetransfer_proto_rawDescData
}

var file_fileproto_filetransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fileproto_filetransfer_proto_goTypes = []interface{}{
	(*FileSegmentRequest)(nil), // 0: fileservice.FileSegmentRequest
	(*FileData)(nil),           // 1: fileservice.FileData
}
var file_fileproto_filetransfer_proto_depIdxs = []int32{
	0, // 0: fileservice.FileService.GetFileChunk:input_type -> fileservice.FileSegmentRequest
	1, // 1: fileservice.FileService.GetFileChunk:output_type -> fileservice.FileData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileproto_filetransfer_proto_init() }
func file_fileproto_filetransfer_proto_init() {
	if File_fileproto_filetransfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fileproto_filetransfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fileproto_filetransfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fileproto_filetransfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileproto_filetransfer_proto_goTypes,
		DependencyIndexes: file_fileproto_filetransfer_proto_depIdxs,
		MessageInfos:      file_fileproto_filetransfer_proto_msgTypes,
	}.Build()
	File_fileproto_filetransfer_proto = out.File
	file_fileproto_filetransfer_proto_rawDesc = nil
	file_fileproto_filetransfer_proto_goTypes = nil
	file_fileproto_filetransfer_proto_depIdxs = nil
}
